### ISSUE TITLE
Missing Commons files?

### ISSUE THREAD

**Issue by TigerHix** [hebiiro/AviUtl-Plugin-ShowWaveform#1]
Hi there,

First of all, awesome work! This is a great AviUtl plugin.

I would like to localize it into my language. However, I don't see the Commons folder anywhere, and this repo seems to be private: https://github.com/hebiiro/Common-Library

Would it be possible to share the code in the Commons folder? Thanks!

**Comment by mitosagi** [comment]
It looks like the Common-Library repository had already been a public repository.
