### ISSUE TITLE
設定なしで使えるようにする

### ISSUE THREAD

**Issue by mitosagi** [hebiiro/AviUtl-Plugin-ShowWaveform#2]
このプラグインを導入した人はサムネイル画像にあるような洗練された拡張編集画面を早く見たい！と思っていることでしょう。
初期設定として
- `updateMode=2`
- 最大値で音声波形をスケーリングする`scaleDiv=auto`のようなモード

を設定する変更は可能ですか？

**Comment by hebiiro** [comment]
updateMode=2 を初期値にするとプロジェクトを読み込んだ瞬間フリーズしたようになって設定を変えることすらできなくなるので無理です。

**Comment by mitosagi** [comment]
お返事ありがとうございます。
初期設定にするのは難しいのですね…
