### ISSUE TITLE
特定のWAVファイルで音声波形が作られません。

### ISSUE THREAD

**Issue by SyoshinsyaAviutl** [hebiiro/AviUtl-Plugin-ShowWaveform#3]
![キャプチャ](https://user-images.githubusercontent.com/128683623/227140965-8bd9dca8-12ba-4c65-9866-02ab74ebdd5f.PNG)
はじめまして蛇色さんの制作されたプラグインにいつも大変お世話になっております。
今回バグのような物を発見したのでこの場を借りて報告させていただきます。

先日アップデートされたアイテム内音声波形 4.0.1にて特定のWAVファイルで音声波形が作られませんでした。
※入力プラグインでの優先度をWaveとL-SNASHで入れ替えても音声波形は作られませんでした。

具体的に言いますと以下の楽曲をダウンロードしてそのまま使うと音声波形が作られませんでした。
※この他にも効果音なのどの一部のWAVファイルで音声波形が作られませんでした。

【しゃろうsuperstar】
https://dl.tracks.co.jp/?m=c3dfb7

検証した環境での主なプラグイン
AviUtl　バージョン 1.10(patched r43_ss_10)
拡張編集version 0.92
InputPipePlugin version 1.10
アイテム内音声波形 3.1.0～4.0.1 全てで一部のWavで波形が作られませんでした。
L-SMASH Works File Reader r1103 by Mr-Ojii
L-SMASH Works Dumper r1103 by Mr-Ojii
L-SMASH Works Muxer r1103 by Mr-Ojii
L-SMASH Works Color Space Converter r1103 by Mr-Ojii

検証は最小構成でやったつもりですが私の環境のせいでしたら申し訳ありません。

**Comment by hebiiro** [comment]
5.0.0 で対応しました。

**Comment by SyoshinsyaAviutl** [comment]
返信、そして対応ありがとうございます。
これからも頑張って下さい。
