### ISSUE TITLE
32bitの環境下で起動しません。

### ISSUE THREAD

**Issue by plumetabnormal** [hebiiro/AviUtl-Plugin-ShowWaveform#4]
こんにちは、へびいろさん。
趣味で動画編集をやろうとしている者です。
当初「音声波形が見える」というプラグインを見つけ、とてもワクワクしていました。
すげーです。かんしゃかんしゃ

起動後、全体の音声波形表示の設定のダイアログが表示された→ウィンドウが空白になっていて、
音声波形も表示されず。更新ボタンを押しても無反応、、という状況です

![スクリーンショット 2024-03-25 215109](https://github.com/hebiiro/AviUtl-Plugin-ShowWaveform/assets/143934323/0f76b4a1-237d-4f19-a321-d20a624f3a4a)

発生している問題について感じたこととして、
・読み取ることは可能→プラグインとしては問題がない
・設定画面などが描画されなかったり、
　多少設定GUIなどが表示されても「ペンの色を選択」などを触ろうとすると落ちたりする
　→プラグイン自体が実行できていないのかな？と思いました。

以下、実行環境についての説明です
・AviUtl 1.10　+　拡張編集 0.92  「Omake」 に掲載されているものをそのまま使用しています
・L-SMASH-Works_r1115_Mr-Ojii_Mr-Ojii.zip 最新版です ちょっと前に更新されていました

そしてPCが、 win10の x86 32bit 仕様なんです。
他のプラグインの 「64」とついたタイプのauiかagi ファイルを導入できませんでした。当然。

GitHubの機能の、プログラムファイル内の利用言語の割合を見て思い出したのですが
「C++」の実行環境についてです。
すでにVisual C++の「 x86」「x64」は導入してあるんです。もちろん再起動も。

どうすれば、起動するんでしょうか。

長文を読ませてしまってすみません。解答よろしくお願いします。

**Comment by hebiiro** [comment]
https://saving-wedding.com/introduction-aviutl/
> 拡張編集プラグインの説明に (AviUtl、拡張編集ともに初めてな方は下のOmakeにある拡張編集セットを使うと導入が少し楽です) とありますが、拡張編集セットは本体のバージョンが0.99m、拡張編集プラグインのバージョンが0.90c2と、最新版ではありません。それぞれ個別にダウンロードしましょう。

ということなので、Omakeは使用しないでください。AviUtl1.10と拡張編集0.92を個別にダウンロードして使用してください。

**Comment by plumetabnormal** [comment]
回答ありがとうございます。
64bitの環境で、Omakeを使わずに構築したら成功しました。ありがとうございます

……32bit 環境許すまじ……
